### PR TITLE
Error handling

### PR DESCRIPTION
**Pull request by Benjamin-Braker**
Added error handling to input fields and added page error and success messages for the following for all pages.

Added CSS to make the error messages work cleanly.

Fixed a few minor issues like adding a 'new report' button to report list and cleaned up report appearance.

### CODE REVIEW

**Comment by Benjamin-Braker** [comment]
Merged new changes from master in.

**Comment by Rycieos** [comment]
You actually don't have to do that, but it is fine.

**Comment by Rycieos** [comment]
I say most of this looks good. There are a few problems, but most are not really an issue.

The only one I think should get fixed is that you can submit an empty comment. It doesn't show up, but the message says that it was saved.

**Comment by Benjamin-Braker** [comment]
I will fix that quickly.

**Comment by Benjamin-Braker** [comment]
Fixed.

**Comment by Rycieos** [comment]
Looks good.

**Pull request merged**
