### PR TITLE
Added eval pages.

### LINKED ISSUE #12: Create tutor evaluation page
Add pages to display evaluation information for tutors (single and list)
        Due by: Tues. Apr 19th

### PR DESCRIPTION
**Pull request by Rycieos**
Added evals list page that is filled with all tutors.
Added eval page that shows all assignments for the tutor.
Eval page shows number of assignments, number of reports, average session time in minutes, and average report length in words.
Added eval button to a tutor's user page for admins.
Added evals button to the admin navigation.
Removed some leftover sorting code on the users page.
Fixes #12

### CODE REVIEW

**Comment by Benjamin-Braker** [comment]
Problem with evals: Some of the tutors do not have any assignments and their tutor eval page causes a division by 0 error.

**Comment by Rycieos** [comment]
Do you have an example tutor that I can view?

**Comment by Benjamin-Braker** [comment]
Aaron Santucci is one that is causing the division by 0 error.

**Comment by Benjamin-Braker** [comment]
Seems to work on your's by my dev is causing errors.

**Comment by Rycieos** [comment]
That is because I just fixed it. Should be good now.

**Comment by Benjamin-Braker** [comment]
Looks good now.

**Pull request merged**
