### PR TITLE
Report page revamp

### PR DESCRIPTION
**Pull request by Benjamin-Braker**
Changed all report questions to use text-areas instead of inputs and update their labels to provide more information.

Updated the database to have a session date instead of submit date.

Updated the controller to convert the date and times into a DateTime object for storage

Added a data-list linked to the start and end times to show the proper format of time.

Updated all display pages to show dates and times in proper format.

### CODE REVIEW

**Comment by Benjamin-Braker** [comment]
Had to make some additional fixes as I did not check my work from a tutor stand point.

**Comment by Rycieos** [comment]
I know you said you had stuff to fix, but I figured I might as well list my found problems.

Report form lets you post without filling in any text boxes.
When editing, Time dropdowns only have the pre-entered time as an option (same with student dropdown).

Is the student dropdown on new report really needed? Seems like it could be confusing...

**Comment by Benjamin-Braker** [comment]
I did not add any additional error handling to the report adding and editing pages as error handling should probably be a full branch on its own. The time dropdowns are just suggestions based on what you have typed in so far but you can just type in what you want. They are not ideal but they are better than what was there. Again no error handling is in place for the times and if invalid values are entered it will save them as midnight. The student dropdown is actually details about the assignment and allows you to change which assignment the report will be tied to. This is helpful as it allows new reports to be added without going through an assignment.

**Comment by Rycieos** [comment]
Fair enough.

I did not realized that those were actually text boxes, so that works. I have not tested different formatting for the times as said, but that should be done.

Are you still storing the submit date? We need it to see if they have submitted the report on-time. It should of course not be something the user inputs.

The student dropdown is a good idea, keep it.

If you have fixed the problems you found, you can accept the pull request.

**Comment by Benjamin-Braker** [comment]
I already fixed the problems I mentioned in the commit messages. Also the
timestamps can be used to keep track of when the report is submitted for
evals.

**Comment by Rycieos** [comment]
What is the status on this pull request? Are changes still needed to be made, or is it ready to merge?

**Comment by Benjamin-Braker** [comment]
It is ready to be merged

**Pull request merged**
