### PR TITLE
Restructured controllers to set role security.

### PR DESCRIPTION
**Pull request by Benjamin-Braker**
Updated user create page to include password.

Added more graceful new user error handling.

Created an Access Denied page and updated previous die requests to access denied views.

Split controller functionality down to separate files per page category.

Fixed edits and deletes so that all data is sent in with a Request as a POST.

Restructured controllers with new naming conventions for methods.

Updated routes file to use new controllers.

Updated all views to use new controllers and proper POST requests.

Updated courses table so that department and number are unique not description.

### CODE REVIEW

**Comment by Rycieos** [comment]
NewUser page lets you save a user with just a name, no email or password.

**Comment by Rycieos** [comment]
Access Denied page looks and works good.
Code looks good.

I think that the error checking for new Users or anything new should be fixed. I would like to see at least the new users form fixed for this pull request.

**Comment by Benjamin-Braker** [comment]
I have fixed this issue by requiring all fields to be filled out.

**Comment by Benjamin-Braker** [comment]
Just fixed new course requirements as well.

**Comment by Benjamin-Braker** [comment]
Okay. I have actually Fixed the Course submission. It wasn't able so add any new courses due to a flipped conditional.

**Comment by Rycieos** [comment]
I just did this with the squash and merge feature, which puts your multiple commits into one commit. Let me know if you like that behavior or not.

**Comment by Benjamin-Braker** [comment]
It shows it as a single black dot on master branch instead of having a
separate line on the 'network' graph so in the future it would probably be
best to merge them the way you did my first pull request.

https://github.com/Calvin-TMO/TMO/network

**Comment by Rycieos** [comment]
Fair enough, but we should try to keep our commits clean of bugs then. In other words, don't commit things until you are sure the feature works as intended. Still keep separate features in different commits, just try to cut down on access clutter.

This goes for @WiensCarson too.

**Pull request merged**
