### PR TITLE
Home page

### PR DESCRIPTION
**Pull request by Benjamin-Braker**
Added a sublist for recent reports and comments to the home page.

For admins, recent reports and comments are out of all.

For tutors and professors, recent reports and comments are only from assigned.

Added CSS new features to make it look decent.

### CODE REVIEW

**Comment by Rycieos** [comment]
Code looks good, but the page is somewhat confusing. It is a list, but the columns have no headers to let me know what I am looking at. And there is only one name per report, is that the tutor or the student? Ideally I think we should have both.

I think if you make them tables instead of lists it would help with confusion a lot. They don't need to be sortable since there will be a max of 5 per.

Reports:
Date | Tutor | Student | Course

Comments:
Date | Commenter | Report topic | Comment contents

**Comment by Benjamin-Braker** [comment]
I have made alterations and re-request a pull.

**Comment by Rycieos** [comment]
This looks good. Works as intended as far as I can tell.

This page actually shows a bug that I had guessed might be a problem if a page has more than one sorting table, but it is not huge and unless anyone else can find it, I don't think it is worth the time to do the large rewrite it would take to fix it.

**Comment by Rycieos** [comment]
Small mistake, I referenced this pull request instead of the issue in the commit mesasge. 

Fixed #15

**Pull request merged**
